### ISSUE TITLE
Reset to Bios Menu option

### ISSUE THREAD

**Issue by RevQuixo** [slinga-homebrew/Save-Game-Copier#16]
Not sure this is possible to trigger, but it would be nice to have an exit function for those of us using an ODE to gracefully exit the program.  This could be done by triggering a system reset to "reboot" the Saturn.

**Comment by slinga-homebrew** [comment]
I'm currently hooking ABC + Start to bring the user back to the title screen. You would prefer to have it exit to the built? Maybe I can add a menu option to restart. Shouldn't be hard, I just need to see what function to call.

**Comment by slinga-homebrew** [comment]
I added a reboot option in version 3.2.0. Let me know if that works.
