### ISSUE TITLE
Better error handling for corrupt save files

### ISSUE THREAD

**Issue by RevQuixo** [slinga-homebrew/Save-Game-Copier#17]
I had on my official save cartridge a couple of 1 memory unit junk files..not sure where they came from.  The built-in bios level saturn memory manager had no issue reading the entire contents of the cart, but the Save Game Copier throws an error for listing files until I went in and deleted these junk files.  Not sure if there is a more graceful way of listing or identifying corrupt files in a memory source without throwing an error.

**Comment by slinga-homebrew** [comment]
I'm using Jo Engine which I believe uses the BUP library under the hood. Not sure why there would be a difference. Do you have an example filename so I can try to repro?

**Comment by RevQuixo** [comment]
I don't currently as I deleted the offending files in order to get the copier to ultimately read the directory,  I'll keep an eye out for users who have issues though while using MODE.  The problem though is there is no way to share them as it is a chicken/egg issue.  For whatever reason though the Saturn will happily display corrupt saves but Copier won't.  The only thing I can think of is somehow to loosen whatever validity check is going into the current methodology in Copier.

**Comment by slinga-homebrew** [comment]
I think release 3.6.1 should handle this issue. If not please re-open.
