### ISSUE TITLE
Cartridge Memory will not display more than 32 items

### ISSUE THREAD

**Issue by RevQuixo** [slinga-homebrew/Save-Game-Copier#19]
As reported on TerraOnion discord a user had 60+ items and only the first 32 will display.  He needed to save those off, delete the first 32 and then the rest would display.

**Comment by slinga-homebrew** [comment]
MAX_SAVES is set to 255 so I'm not sure where I messed up. Will have time this weekend to dig into it.

**Comment by slinga-homebrew** [comment]
I can't repro this. I had a CD with 60+ saves and I didn't have an issue with the listing code. I can try testing directly from the cartridge when I get some time.

**Comment by RevQuixo** [comment]
I'll ty to get some more eyeballs on this on my end.

**Comment by RevQuixo** [comment]
![](https://cdn.discordapp.com/attachments/675068352493912081/786283895846862868/image0.jpg)

![](https://cdn.discordapp.com/attachments/675068352493912081/786283987651395635/image0.jpg)

![](https://cdn.discordapp.com/attachments/675068352493912081/786284009906896936/image0.jpg)

vampire savior, winter heat, and x-men vs sf are missing from the cartridge memory view in SGC (and possibly more)

**Comment by RevQuixo** [comment]
I have 66 items on my cartridge and it is only showing 66

**Comment by slinga-homebrew** [comment]
Lol just like the other thread I'm stumped. I buildta debug version with extra logging to help diagnose: https://github.com/slinga-homebrew/Save-Game-Copier/releases/tag/3.2.2.1. 

Basically I print out the count of saves multiple times. Can you tell me those numbers?

**Comment by slinga-homebrew** [comment]
Ok looks like I was able to repro the issue. There's a cap to 32 files for some reason. I'll look through Jo Source.

**Comment by slinga-homebrew** [comment]
In Jo Engine's backup.h:

# define JO_BACKUP_MAX_FILE                 (32)

What do you think is a reasonable amount? 128?

**Comment by RevQuixo** [comment]
Is 255 to match the max saves too much?  I had 66 saves on my card and still 4,000 blocks free, So I can see going over 128 easily.

**Comment by slinga-homebrew** [comment]
This appears fixed with the newest Jo Engine. I'll make a new release tomorrow.

**Comment by slinga-homebrew** [comment]
https://github.com/slinga-homebrew/Save-Game-Copier/releases/tag/3.2.3

Let me know if you have any issues.
