### ISSUE TITLE
Paging for browsing save files and alphanumeric sorting

### ISSUE THREAD

**Issue by amerika13** [slinga-homebrew/Save-Game-Copier#22]
I ran into an issue while researching an issue yesterday where I had nearly 100 saves to sort through in my directory. And it will become harder with more people trading save files.

You have to individually tap down to get through every save file. You cannot hold down to keep moving. You also can't press left or right to page quickly. So when you get up to 30+ save files, that can start getting rough. When you get to even more, it will be extremely hard.  Also, there was no alphanumeric sorting being applied so many of the saves were out of order compounding the issue.

Thank you!

**Comment by slinga-homebrew** [comment]
Yeah I can add something to navigate by pages. Something like Left Trigger\Right Trigger. 

The saves aren't sorted in the internal memory either. Shouldn't be hard to implement a sort.

**Comment by amerika13** [comment]
Thank you! I am not the biggest fan of using L+R on top of controllers to page since L+R on the dpad isn't used for anything else. Might as well keep paging on the Dpad too. But up to you!

**Comment by VGKintsugi** [comment]
Sure that sounds reasonable.

**Comment by slinga-homebrew** [comment]
Saves appear to be sorted now. L\R appears to go to to the next page. I haven't tested much. 

Are you comfortable building this? Or should I tag a debug release?

**Comment by amerika13** [comment]
> Saves appear to be sorted now. L\R appears to go to to the next page. I haven't tested much.
> 
> Are you comfortable building this? Or should I tag a debug release?

Tag a debug please if you don't mind.

**Comment by slinga-homebrew** [comment]
https://github.com/slinga-homebrew/Save-Game-Copier/releases/tag/3.2.1
