### ISSUE TITLE
When Soft Reset to Menu option on Terraonion MODE is set to "CDPlayer->MODE" Save Game Copier does not load

### ISSUE THREAD

**Issue by SpaceCoyot3** [slinga-homebrew/Save-Game-Copier#31]
Running MODE firmware 1.04 and using SGC 3.5.0 and I just changed the Soft Reset to Menu option to "CDPlayer->MODE" and now Save Game Copier does not load (blank black screen). When I change this setting to either of the two other Reset options, SGC loads just fine.

**Comment by slinga-homebrew** [comment]
I don't own a MODE, what does the "CDPlayer->MODE" option do? Does it hook ABC+Start?

I can ask the TerraOnion devs for advice as well.

**Comment by SpaceCoyot3** [comment]
The "CDPlayer->MODE" setting makes it so when you press the physical reset button on the console, the Saturn will restart to the CP player screen where you can Start Application, Eject, Play/Pause, etc. Then when you select Start Application, you go back into the MODE start screen.

**Comment by slinga-homebrew** [comment]
I'm not sure why this wouldn't work. I would have to ask TerraOnion to take a look.

**Comment by RevQuixo** [comment]
@Terraonion-dev will have to comment on the specifics, but the option is one that hooks into the reset code to allow you to soft boot back out to the CD menu.   It is not compatible with all games.  I more compatible option is to turn on fast boot and change the option to "Driect to Mode" this works last I checked.  Alternatively you could create a "mode.cfg" (a simple text file) with the following "Flags=0" (without the quotes) and place it in the same folder as the SGC.  This will override the soft reset settings.

**Comment by SpaceCoyot3** [comment]
Awesome - thanks for the .cfg suggestion, @RevQuixo!

**Comment by slinga-homebrew** [comment]
Thanks Rev, closing.
