### ISSUE TITLE
I got error message of "Failed to copy the save ,Possibly due to a lack of space."

### ISSUE THREAD

**Issue by dogos1** [slinga-homebrew/Save-Game-Copier#37]
I have played falcom classic2 in mednafen emulator,But A few days ago,I feel like to play falcom classic2 in my japanese saturn  from savestate of mednafen emulator.
So,I extract raw save data from bkr extension file of mednafen emulator.(I use ss-save-parser 0.96 of below link in order to extract raw date from bkr file)
[ ss-save-parser 0.96](https://github.com/hitomi2500/ss-save-parser/releases)

I converted raw save data file to BUP file and verified that it is correct BUP file by running below command in Windows CMD commands
`python3 bup_parse.py --input_bup falcom_c.BUP `
I add this bup file to SGC ISO with Winiso and Burned this SGC ISO with imgburn.
I inserted this burn disc into cd tray of japanese saturn and got into  Save game copier menu.
I selected CD file SYSTEM and select falcom_c.bup file from list But it display below screenshot of 
"Failed to copy the save ,Possibly due to a lack of space."
[Error message of Save game copier](https://i.ibb.co/HYhPbBL/20210307-161825I-1.jpg)
I don't have action replay or any other external cartridge ,I only use internal memory which is maintained by CR2032 battery..
Is there any ways to copy my savedata from mednafen into internal memory of japanese saturn?

For your information below link is BUP file which I tried to copy it into internal memory of saturn.
https://www.dropbox.com/s/30hnoktnlcqgxq7/FALCOM_C.BUP?dl=0

any reply would be appreciated.

**Comment by dogos1** [comment]
I trimed(truncate) size of bkr extension files with HxD utility(remove most of 0 hex value from the middle part.)
I converted extracted raw save data to BUP file and copy it to internal memory of saturn,But it seems that Falcom classic2 doesn't recognized this save data which came from  mednafen emulator. 
Is there any way to make save data of mednafen emulator compatibility with japanese saturn hardware?

**Comment by slinga-homebrew** [comment]
Can you boot SGC on mednafen and take a screenshot of the falcom_c save game? Just glancing at the size the first issue I see is that the data size is set to 32k. That's the size of the entire internal memory. So what I think happened is the .bkr file contains all of internal memory, not just the falcom save. 

ss-save-parser has been updated to support .BUP files. I can ask @hitomi2500 to make a new release. 

```
python3 bup_parse.py --input_bup FALCOM_C.BUP
Validating FALCOM_C.BUP
	Save name: falcom_c
	Comment: SGC
	Language: English
	Date: 1994-11-24 00:00:00 (0x778da0)
	Data Size: 32768
	Block Size: 1
	MD5: cdb5b446b628393f76e4032e4c6c8ba8
Valid .BUP file
```

**Comment by slinga-homebrew** [comment]
Can you upload the original .BKR file as well?

**Comment by dogos1** [comment]
below link is original BKR extension file which came from mednafen.

https://www.dropbox.com/s/zdbwx64a0wy9iob/FALCOM_CLASSICS2.607230fd13bd319fc8d4f2955e369d91.bkr?
dl=0

I already changed falcom_c.bup with trimed size of 507 byte in SGC ISO..

**Comment by slinga-homebrew** [comment]
The screenshot would list the original MD5 sum of the file. It would make debugging easier.

**Comment by slinga-homebrew** [comment]
Running SS-save-parse I see two save files: 
![saves](https://user-images.githubusercontent.com/58894244/110250381-064d4700-7f49-11eb-8993-0a94af92d70e.png)

[saves.zip](https://github.com/slinga-homebrew/Save-Game-Copier/files/6097730/saves.zip)

**Comment by dogos1** [comment]
I tested these bup file on japanese hi saturn mmp11,When I started to play Falcomclassic2, these save file was surely recognized..But An error message displayed in japanese that "It is impossible to load the game exiting record (FALCOMC2COM). Please delete this record in the savedata manager screen of your saturn."

https://i.ibb.co/pZzqNBS/20210308-115200-1.jpg

I think I need more solution in  savefile of FALCOMC2COM..

**Comment by slinga-homebrew** [comment]
Glad you were able to get it to work. In the future SS-save-parser will have the ability to export directly to .BUP.
