### ISSUE TITLE
Implement save compression/decompression?

### ISSUE THREAD

**Issue by eaudunord** [slinga-homebrew/Save-Game-Copier#38]
Compression and decompression was implemented in the rockin-b save game manager http://www.rockin-b.de/saturn-savegamemanager.html but honestly this program is much more intuitive to navigate and use and supports more devices. I would love to see the ability to compress/decompress individual saves combined with the copy function. For example a function to copy as a compressed save from backup cartridge to internal memory and vice versa with decompression. Is anything like this in your roadmap?

**Comment by slinga-homebrew** [comment]
Thanks for the suggestion. At this time I don't plan to add compression\decompression. Would it be possible for you to buy a bigger backup cartridge? Another option would be to use a Satiator or MODE which SGC can copy saves to. I realize that is a costly option.

**Comment by eaudunord** [comment]
Thanks for the response. The use case I was thinking about was with saves that are too large for the internal memory. To transfer a large save from one cartridge to another it could be compressed, copied to internal memory, then copied to the other cartridge. It would also make backing up and sharing via Netlink possible. I realize a Mode or Satiator would solve the issue.

**Comment by slinga-homebrew** [comment]
Would Save Game Extractor be a potential option (https://github.com/slinga-homebrew/Save-Game-Extractor)? It let's you extract saves via audio. You need to plug the Saturn's audio into the line-in of your PC.
