### ISSUE TITLE
Add a backup/write option for cart firmware.

### ISSUE THREAD

**Issue by mathieulh** [slinga-homebrew/Save-Game-Copier#42]
It would be nice to have a way to dump the cartridge firmware/rom and/or write it to an external device (such as MODE for example); some rare cartridges have yet to be dumped.

**Comment by slinga-homebrew** [comment]
The "Dump Memory" option already supports this use case. From my notes the cartridge is at: Cartridge backup memory (address: 0x02000000, size: 0x01FFFFFF). 

Let me know if that is what you are looking for.
