### ISSUE TITLE
action replay saves missing file extension when saving to satiator

### ISSUE THREAD

**Issue by LXXero** [slinga-homebrew/Save-Game-Copier#46]
Hi, I was trying to copy games from my action replay to my satiator, and it seems to be missing the .BUP extension when it puts them in the folder, and in turn they aren't visible when you view the saves on the satiator.

Copying from internal memory works as expected, it's only when copying from action replay that this seems to happen

**Comment by slinga-homebrew** [comment]
Let me know if this fixed it: https://github.com/slinga-homebrew/Save-Game-Copier/releases/tag/3.6.11. 

I didn't have time to test it.

**Comment by LXXero** [comment]
still no go

**Comment by slinga-homebrew** [comment]
Appears fixed in 3.6.12.
