### ISSUE TITLE
Testing Save-Game-Copier with Terraonion MODE

### ISSUE THREAD

**Issue by amerika13** [slinga-homebrew/Save-Game-Copier#5]
Hello!

I just wanted to report that I was able to use your Save-Game-Copier fairly successfully with TO's MODE internal ODE.

I was able to:
1. See both internal and official sega cart saves
2. Copy saves between internal and cart
3. Copy from CD memory to both internal and cart

Issues found:
1. If you choose the Satiator option the Saturn will freeze. Which that or an error screen would be expected as I do not have a Satiator.  This should probably get a graceful error added similar to what happens with other functions that are performed but don't work.
2. It cannot read Pro Action Replay (PAR) saves. I am using an unflashed cart. I know this is due to PAR compressing the saves (possibly encrypting?) and it would be nice if your program could read them if possible.
3. No ability to write to MODE.  This is expected as this application was not built for interaction with MODE...yet. However, integration would be amazing and I'd wager Alex and Neodev (the main developer) would entertain the idea at least.

Even if nothings comes of this, I would like to say thanks as this is a very quick and handy save game utility I can easily boot from MODE to manage my saves. So that alone is very much appreciated. And it also seems as though I could add saves to my Saturn by modifying the ISO. Which could also prove quite handy.

Thank you,

Michael

**Comment by douglie007** [comment]
I wonder if you could make the program think the CD replacement drives like the mode and Fenrir is a burner and create an iso of the saves.  But the program would have to run in the memory to free up the "drive".

**Comment by slinga-homebrew** [comment]
Sorry just saw this, 

1) I spoke Professor Abrasive about how to safely detect the presence of the Satiator. Basically I need to timeout and fail. Should be easy to implement. Will be in the next release. 
2) I don't have a PAR to test on. I'm assuming the Saturn BIOS cannot see it either? Or can the Saturn BIOS see it and the save content doesn't make sense? If I can find documentation on how the saves are compressed (unlikely to be encrypted) I will consider adding PAR support. 
3) I don't have a MODE (or any ODE lol). The unique thing about Satiator is that he Professor Abrasive is able to intercept calls to the mpeg card. He wrote API which I used to read\write from the Satiator SD card. I don't believe the MODE or any other ODE has such an ability. 
4) And yes you should be able to insert additional saves into the ISO. I have been meaning to add instructions on how to do it. 

Lol @douglie007. You are an optimist, the Saturn doesn't quite work that way.
