### ISSUE TITLE
Serial connection?

### ISSUE THREAD

**Issue by douglie007** [slinga-homebrew/Save-Game-Copier#6]
Staying optimistic, how does it communicate with the serial adapter to right to a floppy drive?  Being that they are not easy to get, maybe someone could make an external saver to an SD card to directly to a pc. I dont have 300 for a A saturator so I'm thinking of was I could backup my saves externally.

**Comment by slinga-homebrew** [comment]
I'm using Jo Engine's library to talk to the floppy drive. I'm not sure how the serial port works. But yeah it should be possible for some one to make a device that works on the serial port.
